### ISSUE TITLE
/help command needs to filter out github

### ISSUE THREAD

**Issue by zachmmeyer** [codyloyd/odin-bot-v2#31]
We're linking the github help pages, which starts out as  /help.github.

Obviously there is a way to filter out the github links, I am not skilled enough yet to make my own PR. It's just frustrating.

**Comment by olav35** [comment]
Made a PR that fixes the issue.

https://github.com/codyloyd/odin-bot-v2/pull/33

**Comment by zachmmeyer** [comment]
GitHub changed from help to docs in their url, so this isn't an issue anymore.
